theme: jekyll-theme-minimal

title: N I L E
description: The Novel Irrigation and Land use Efficiency Blog

logo: /assets/logo.png
link rel="shortcut icon" type="image/x-icon" href="{{ '/assets/favicon.ico' | relative_url }}"
